# Generated by Django 4.2.25 on 2025-11-06 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0003_alter_book_options_alter_book_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['-borrowed_at'], 'verbose_name': 'Empréstimo', 'verbose_name_plural': 'Empréstimos'},
        ),
        migrations.RemoveField(
            model_name='loan',
            name='loan_date',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='return_date',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('ficcao', 'Ficção'), ('nao_ficcao', 'Não Ficção'), ('infantil', 'Infantil'), ('tecnico', 'Técnico'), ('outro', 'Outro')], default='outro', max_length=50, verbose_name='Gênero'),
        ),
        migrations.AddField(
            model_name='loan',
            name='borrowed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data do Empréstimo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Devolução'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='Livro'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
