# Generated by Django 4.2 on 2025-11-08 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_loan_book_alter_loan_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='loan',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.UniqueConstraint(condition=models.Q(('returned', False)), fields=('user', 'book'), name='unique_active_loan'),
        ),
    ]
