# Generated by Django 4.2 on 2025-11-08 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_book_options_book_genre_alter_book_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(help_text='Nome do autor ou autores do livro.', max_length=200, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='book',
            name='available',
            field=models.BooleanField(default=True, help_text='Indica se o livro está disponível para empréstimo.', verbose_name='Disponível'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Imagem da capa do livro.', null=True, upload_to='covers/', verbose_name='Capa do Livro'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, help_text='Breve resumo ou sinopse do livro.', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, choices=[('Romance', 'Romance'), ('Aventura', 'Aventura'), ('Terror', 'Terror'), ('Fantasia', 'Fantasia'), ('História', 'História'), ('Biografia', 'Biografia'), ('Outros', 'Outros')], help_text='Selecione o gênero literário.', max_length=100, null=True, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_year',
            field=models.PositiveIntegerField(blank=True, help_text='Ano em que o livro foi publicado.', null=True, verbose_name='Ano de Publicação'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(help_text='Título completo do livro.', max_length=200, verbose_name='Título'),
        ),
    ]
