# Generated by Django 4.2 on 2025-11-09 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_book_author_alter_book_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Imagem da capa do livro (preferencialmente formato JPG ou PNG).', null=True, upload_to='covers/', verbose_name='Capa do Livro'),
        ),
    ]
